# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evolv', '0005_auto_20161216_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='followup_period',
            field=models.PositiveSmallIntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='contact',
            name='followup',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 21, 30, 11, 180257, tzinfo=utc), verbose_name='Follow up Date'),
        ),
    ]
